meta_title: "Comparateur de prix de Sneakers - SEVA"
meta_description: "Recherchez et comparez parmi 29 sites de sneakers en un clic"
meta_image: "home.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@Seva_bzh"